### ISSUE TITLE
truncated octahedron box in solvation

### ISSUE THREAD

**Issue by isjoung** [openmm/openmm-setup#18]
https://github.com/openmm/openmm-setup/blob/e6930a0cc47b2b98de98a157f89c9a3ea75d5a57/openmmsetup/openmmsetup.py#L252
Truncated octahedron vectors are odd. The third vector is -1/3,sqrt(2)/3,sqrt(6)/3 ??
Amber-style vectors are (1,0,0), (-1/3,2sqrt(2)/3,0), (-1/3,-sqrt(2)/3,sqrt(6)/3).

**Comment by peastman** [comment]
I believe you're right, the second element of the third vector should be sqrt(2)/3, not 1/3.  I'll fix it here and also in PDBFixer.
