### ISSUE TITLE
Feature request: Export system/integrator as XML

### ISSUE THREAD

**Issue by dwhswenson** [openmm/openmm-setup#28]
Other tools that integrate with OpenMM can use the system/integrator XML serialization as user-provided inputs. In particular, I'm trying to establish a Python-free workflow in OpenPathSampling, using new tools for simulation setup from the upcoming release of our [command line interface](http://github.com/openpathsampling/openpathsampling-cli). We take system/integrator XML files as input for OpenMM, and I'm not aware of a Python-free way to export those as XML. (Granted, the requisite Python is a pretty small step once a user has the script from openmm-setup, but I'm aiming for zero user-written Python.) 

 I'd be happy to try to contribute the feature myself (gives me an excuse to learn about working with Flask). However, there are probably several ways to implement this, so I'd like to check that my suggested approach makes sense before starting a PR.

I think the most straightforward way to do this would be to add the following checkboxes at the bottom of the "Output" configuration tab (with associated textboxes for filename when the checkbox is enabled):

* **Save final configuration to a PDB file** (I think this would be more straightforward to continue with other tools than working with the DCD)
* **Save system to an XML file**
* **Save integrator to an XML file**

From that, I could tell my users to enable those options (and possibly to perform no minimization/equilibration/simulation if they're happy with their initial PDB input). The XML files would only be created if the user runs the script -- they would not be packaged in the zip that comes from the "Save All Files" button.

**Comment by peastman** [comment]
Are you asking for the XML files to be generated by OpenMM-Setup, or to be generated by the script it produces?  If your goal is to enable a Python free workflow (other than OpenMM-Setup itself, of course), I would think the former would be more useful?

**Comment by dwhswenson** [comment]
To clarify, when I say "Python-free workflow", I mean "without the end user writing Python code" -- not without using Python at all. I'm working on user experience for people who are not comfortable using a Python library/writing their own Python scripts. But the tools I'm developing are all written in Python.

I think either of the following would provide a good experience for users:

1. A way to generate the XML files without actually running the full script. If all you want is system.xml and integrator.xml, you don't need to actually do anything that *uses* the `app.Simulation` object (energy min, equil, etc.).

2. A way to generate the XML files as an optional byproduct of running the script. Since the script can be run in-browser, this is still no-Python from the user perspective. (Most importantly, users don't need to manually write Python code.)

In some ways, the first approach may be easier for the specific users I would be sending here, but I think the second approach may be better (and was more what I was suggesting) for a few reasons:

* One thing I like about OpenMM-Setup is that it is good as a teaching tool. Users click on the checkboxes and fill in the fields, and they can see the resulting Python script. It helps Python beginners bridge between their knowledge of MD programs and the idea of using OpenMM as a library. Putting the code to generate the XML in the script feels better aligned with that aspect of OpenMM-Setup.
* I'm not sure how the first approach would be exposed in the UI. Maybe including the XML in "Save All Files;" otherwise it would need a separate button alongside those, but I'm not sure how to label such a button in a way that doesn't risk confusion for the users who don't need it.
* Adding a few options at the bottom of the Output config tab seems like a relatively small change in UI that would be unlikely to confuse or disrupt current users. This seems like the natural location if the files are byproducts of the script; if they're generated another way, then it would make more sense to put them under the system/integrator tabs.
* Implementation of the second approach looks easier (from a brief glance at the code base, at least).

**Comment by peastman** [comment]
That sounds reasonable.  If you want to create a PR, that would be great.

Would it be better to save the final conformation in PDBx/mmCIF format instead of PDB?  I know there are still some programs that don't support it, but they really need to.  It's been the official standard for years.
